### PR TITLE
bump optim

### LINKED ISSUE #79: Extend or bump [compat] for Optim.jl

### PR DESCRIPTION
**Pull request by tlienart**
closes #79

### CODE REVIEW

**Comment by tlienart** [comment]
there's a problem with MLJBase (?) see https://github.com/alan-turing-institute/MLJBase.jl/issues/425

**Comment by OkonSamuel** [comment]
@tlienart have you tried deleting the **MLJBase** folder from your `path_to_julia_folder/.julia/packages/`  directory and the reinstalling MLJBase. 
I'm unable to reproduce this issue on my system. Am running ubuntu by the way.

**Comment by tlienart** [comment]
thanks Sam, yes, I did; seems like it might be a thing with JLSO or Memento ...

**Comment by OkonSamuel** [comment]
yeah. That's makes much sense. It seems  `MLJLinearModels` call `MLJ.save`

**Comment by tlienart** [comment]
there may be an issue with MLJLinearModels but if you have a look at the issue on MLJBase the error happens independently of it

**Comment by OkonSamuel** [comment]
I still can't reproduce on my pc. @ablaom could you see if you can reproduce this on your mac

**Comment by ablaom** [comment]
No I cannot reproduce. All good in a fresh env on my mac:

```julia
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PATH = /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
```

The fail on 1.0 seems unrelated. It suggests that travis is not building proper R installation. I'm guessing you turned tested with R back on just for a one time test?

**Comment by DilumAluthge** [comment]
I heard that the latest release of Optim has some problems on Julia 1.0.

**Comment by ablaom** [comment]
https://github.com/JuliaNLSolvers/Optim.jl/issues/863

**Comment by OkonSamuel** [comment]
@tlienart I think this has been fixed. Tests for julia v1.0 now pass. see [logs](https://travis-ci.com/github/alan-turing-institute/MLJLinearModels.jl/jobs/382651172). julia nightly tests fails. I suggest allowing failures for julia nightlies.

**Comment by tlienart** [comment]
thanks sam, I updated the travis yml we'll see

**Comment by tlienart** [comment]
lgtm

**Pull request merged**
